### ISSUE TITLE
Move to ember-fastboot org?

### ISSUE THREAD

**Issue by rwjblue** [ember-fastboot/ember-cli-head#72]
Since this is used quite a bit in the FastBoot world, maybe we could move this repo over into the `ember-fastboot` org.

@ronco - What do you think? If that makes sense to you, you can initiate transfer to me then I'll move it into the org. Also, you'll definitely still be an owner there too...

**Comment by ronco** [comment]
I'd be happy to have you take over @rwjblue . I tried to transfer, but it failed as you had an ember-cli-head repo already. Let me know how you'd like me to proceed.

Chners!

**Comment by rwjblue** [comment]
@ronco - I made you an owner over in `ember-fastboot` (you probably have to accept the invite), so you should be able to transfer now. I'll fixup the permissions after we get the repo moved...

**Comment by mansona** [comment]
Hey folks 👋 do you still want to transfer this to the fastboot org?

**Comment by ronco** [comment]
Hey @mansona ,
I've added you to npm and this repo on Github. I missed the invite window for fastboot, so I can't move it atm.  I'm happy to jump on that this time if you send me another invite (or maybe you can do it now that you're a collaborator?).

**Comment by mansona** [comment]
turns out that I don't have permissions to add you to the fastboot org 🙃 maybe you could transfer it to me or make me an owner here and I can transfer it to fastboot?

**Comment by ronco** [comment]
@mansona I can’t figure out how to make you an owner.  Collaborator seems to be the one and only permission level. Other ideas?

**Comment by mansona** [comment]
I guess the only thing to do is a) wait for me to get admin on ember-fastboot or b) transfer to me and I'll transfer it in

**Comment by ronco** [comment]
@mansona , alright, I sent a transfer request.

**Comment by mansona** [comment]
😫 

Apparently repository transfer requests expire in `about a day` so I wasn't quick enough off the mark on that one. I understand there are safety concerns on things like this but 24 hours seems a bit too tight 😞 

Can you send it again?

**Comment by ronco** [comment]
@mansona , alright, sent it again. 

Cheers

**Comment by mansona** [comment]
Done! 🎉 

Thanks for all that @ronco and sorry for all the complications 🙈
